version: '3'
services:

  backend-server:
    build:
      context: .
      dockerfile: server.docker
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - backend-php-fpm
    ports:
      - "8081:80"
    networks:
      - internal
  backend-php-fpm:
    build:
      context: .
      dockerfile: php-fpm.docker
    environment:
      XDEBUG_CONFIG: "remote_host=192.160.220.1 remote_enable=1"
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - ./backend:/var/www/backend
      - ./storage:/var/www/storage
    depends_on:
      - backend-postgres
      - mailer
    networks:
      - internal

  backend-php:
    build:
      context: .
      dockerfile: php.docker
    volumes:
      - ./backend:/var/www/backend
      - ./storage:/var/www/storage
      - composer:/root/.composer/cache
    depends_on:
      - backend-postgres
      - mailer
    networks:
      - internal

  backend-postgres:
    image: postgres:12.1-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: locked
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: oauth
    ports:
      - "54321:5432"
    networks:
      - internal

  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
    networks:
      - internal


networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.160.220.0/28

volumes:
  backend-postgres:
  composer:
