security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fetcher:
            id: App\Security\ProfileProvider
    encoders:
        App\Security\ProfileByEmail: native
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_token:
            pattern: ^/token$
            security: false
        api:
            pattern: ^/api
            security: true
            anonymous: lazy
            stateless: true
            oauth2: true
        main:
            anonymous: lazy
            user_checker: App\Security\ProfileChecker

    access_control:
        - { path: ^/api/?$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/confirm, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/oauth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
