<?php

namespace App\Tests;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DatabaseWebTest extends WebTestCase
{
    private EntityManagerInterface $entityManager;

    protected KernelBrowser $client;

    protected function setup(): void
    {
        parent::setUp();
        $this->client = sstatic::createClient();
        $this->client->disableReboot();
        $this->entityManager = static::$kernel->getContainer()->get('doctrine')->getManager();
        $this->entityManager->getConnection()->beginTransaction();
        $this->entityManager->getConnection()->setAutoCommit(false);
    }

    protected function tearDown(): void
    {
        $this->entityManager->getConnection()->rollback();
        $this->entityManager->close();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    protected function service(string $serviceId)
    {
        return self::$container->get($serviceId);
    }
}
